### PR TITLE
adding odd-even functionality

### PR DESCRIPTION
**Pull request by Vilax**

### CODE REVIEW

**Comment by Vilax** [comment]
@azazellochg , thanks for going over it so fast. No rush :)

Just adding to avoid overlapping, this modification depends on a refactorization in protocol_ts_motion in scipion-em-tomo plugin

See the PR here, just in case you are working on something similar:

[](https://github.com/scipion-em/scipion-em-tomo/pull/337)

**Comment by azazellochg** [comment]
Hi, I didn't look over this yet, all I noticed is odd even stuff will
become like halfmaps property. Since you are changing the tomo plugin as
well, I will need to go over this again once the base protocols work. Don't
worry, I'll eventually merge this

**Comment by pconesa** [comment]
I'd change this to draft until is changes in tomo are released, so code doe not prevent the release of itself.

**Comment by Vilax** [comment]
@azazellochg just checking the state of the refactorization before merging this PR

**Comment by azazellochg** [comment]
Hi, this cannot be merged before https://github.com/scipion-em/scipion-em-tomo/pull/337

**Comment by Vilax** [comment]
hahaha, then, I think we were waiting in a kind of circular waiting list. Let's go for that PR first. Thanks @azazellochg Grigory

**Comment by azazellochg** [comment]
:) otherwise, my refactoring is done. If core tomo PR is merged, I will check odd/even here and merge this week-end.

**Review by azazellochg — APPROVED** [review]

**Pull request merged**
