### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by DaniDelHoyo**
Flipping (Y) gain image to match tiff movies and properly correct the gain. Final micrograph also flipped (Y) to maintain the orientation with other protocols.

### CODE REVIEW

**Comment by azazellochg** [comment]
That's not how we do things here. Please create a PR to devel branch

**Comment by DaniDelHoyo** [comment]
Hello Grigory,

I would like to apologize. I am quite a noob with Git and I did not realize
that I was directing the PR against the master branch (both for cistem and
motioncorr).
I will be more careful next time, I hope it wasn't a lot of trouble and
that you consider the changes useful.

Best regards,
Daniel

**Comment by azazellochg** [comment]
Hello Daniel,

no problems. I've moved the discussion  here: https://github.com/scipion-em/scipion-em/pull/202

**Comment by delarosatrevin** [comment]
Thank @DaniDelHoyo for the contribution and @azazellochg for checking this. I will also take a look at the changes.

**Pull request closed without merging**
