### PR TITLE
motioncor3 added

### PR DESCRIPTION
**Pull request by azazellochg**
- config vars were renamed to remove the version from the name
- ctf is disabled. At this point, I don't see the reason for its integration if there's gctffind already as a separate package

Both spa and tomo tests pass

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Thanks @azazellochg! I will review this PR, but can't promise before next year. Was it too much hassle to keep the last MC2 version supported?

**Comment by azazellochg** [comment]
Hi,

In my opinion, yes. But I'm open to suggestions

**Comment by azazellochg** [comment]
@delarosatrevin After having another look, I have added old mc2 1.6.4

**Comment by delarosatrevin** [comment]
Thanks Gregory! I think it is good to have a plan B in case there is any
issue with MC3

**Comment by azazellochg** [comment]
While testing I've discovered tat the new binaries need libtiff.so.6, while the previous ones require libtiff.so.5

**Pull request merged**
