### PR TITLE
3.16.1

### PR DESCRIPTION
**Pull request by azazellochg**
3.16.1: bugfix: convert EER gain to mrc
3.16:
    - motioncor3 support
    - all variables renamed to remove specific version from the name

### CODE REVIEW

**Comment by azazellochg** [comment]
TODO: check if tasks still works

**Comment by azazellochg** [comment]
@delarosatrevin I have very strange errors when trying to run tasks protocol with mc2-1.6.4. It cannot find input movies..

**Comment by delarosatrevin** [comment]
Hi @azazellochg , I will try the mc-tasks with this version

**Comment by delarosatrevin** [comment]
What is the format of input movies? I see -InMrc in the command line, is that correct?

**Comment by azazellochg** [comment]
The movies are mrcs (/public/EM/Scipion/scipion-dev/data/tests/movies/Falcon*.mrcs), I can see them linked to mrcs inside the tmp/batchid folder

**Pull request merged**
